export const configApp = {
  apiKey4: 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3NGIzMWVhYThlMmVmZDllYWVhOWUwOGE4M2NiNTVkMyIsInN1YiI6IjVkZDk5MzU1MTJhYWJjMDAxMTkxNzc4ZiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.YiCVUv7A344kmepRE9bQTk1uG0t_-25VTQJtVmxc-9k'
}
// # sourceMappingURL=configApp.js.map
